node_env: "development"
url_db: "postgres://postgres:123456@localhost:5432/crop_service_db?sslmode=disable"
name_service: "CropService"
port_grpc: 50055
host_grpc: "localhost"
interval_check: "20s"
timeout_check: "15s"
